spring:
  datasource:
    url: jdbc:postgresql://192.168.238.12:5432/myappdb
    username: myapp
    password: dkagh1.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080